### ISSUE TITLE
About the GPU performance and memory require

### ISSUE THREAD

**Issue by ltcs11** [yxlijun/DSFD.pytorch#8]
currently i'm using GTX1070(8GB) to test your code and try to retrain with Resnet
the "out of memory" problem is very common, so i have to change the max_im_shrink in your wider_test.py file
and while retraing the network, i can only set the batch size less than 6 to avoid the OOM problem 
using GTX1070(8GB) can get the inference time(from wider_test.py) as 0.5s-1.5s(after shrinking the pic size into 750*500)
*im using pytorch 0.3 with cuda 8

so what's your GPU device status(both memory and inference time)? Am I getting the right GPU performance?

**Comment by yxlijun** [comment]
My GPU Is GTX1080(12GB),you can reduce the parameter max_im_shrink  in wider_test.py

**Comment by ltcs11** [comment]
> My GPU Is GTX1080(12GB),you can reduce the parameter max_im_shrink in wider_test.py

thx! And what about your inference time?

**Comment by hanjw123** [comment]
1080*720 input size，GTX1060，inference time 2s

**Comment by rogrt** [comment]
请问一下，训练时总是死机重启是怎么回事呢，1080的
