### ISSUE TITLE
Error during testing on wider face dataset

### ISSUE THREAD

**Issue by testingshanu** [yxlijun/DSFD.pytorch#9]
Hey,
Thank you for the implementation of DSFD.
While testing on the wider eval dataset, I am getting an error from detection.py as follows:

**ids, count = nms(boxes_, scores, self.nms_thresh, self.nms_top_k)
ValueError: not enough values to unpack (expected 2, got 0)**

My intuition is that if a face is not detected, then nms function is not able to refine the bbox and return the same. Correct me if I am wrong. 

Also is there a solution to fix it. 

Thank you,

**Comment by Ir1d** [comment]
```
return keep, 0
```

https://github.com/yxlijun/DSFD.pytorch/blob/master/layers/bbox_utils.py#L260

**Comment by testingshanu** [comment]
Thank you
